version: '3'
services:
  airprint:
    image: airprint:latest
    container_name: airprint
    build:
        context: ../projects/airprint/
        dockerfile: Dockerfile
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - CUPSADMIN=admin #optional
      - CUPSPASSWORD=password #optional
    volumes:
      - /opt/airprint/services:/services
      - /opt/airprint/config:/config
      - /var/run/dbus:/var/run/dbus
    restart: unless-stopped
